# Generated by Django 3.2.7 on 2021-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserkId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=500)),
            ],
        ),
    ]
